module.exports = [
  'AI',
  'Kartik Chincholikar',
  'course',
  'Data Science',
  'Machine Learning',
  'mooc',
  'mooc.en',
  'Domain Experts',
  'Subject Matter Experts',
  'Industry Professionals',
  'Feasibility',
  'LLM',
  'Large Language Models',
  'Science',
  'Arts',
  'Humanities',
  'Business',
  'learn',
  'Coursera',
  'workshop',
  'no bullshit',
  'Artificial Intelligence',
  'Manufacturing',
  'Deep Learning',
  'Applied',
  'AI powered',
  'google',
  'virtual',
  'graphs',
  'protein',
  'biotech',
  'medicine',
  'chatgpt'
];
