name: build and deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '10.x'
      - name: install
        run: |
          npm install
      - name: build
        run: |
          ls -la
          npm run build
      - name: git status
        run: |
          git status          
      - name: working dir
        run: |
          cd public 
          pwd
          ls -la
      - name: wtf
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
 